site_name: AuRORA

repo_name: 'AuRORA-doc'
repo_url: https://github.com/LabTelecomUnB/AuRORA-doc
site_url: https://labtelecomunb.github.io/AuRORA-doc/
edit_uri: edit/main/docs/

# copyright: Copyright & copy; 2024 Nome do app

extra_css:
  - assets/stylesheets/custom.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/logo-theme.js


theme:
  custom_dir: overrides
  name: material
  language: pt-BR
  favicon: assets/images/favicon.png

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.top

  hide: 
    - 
    
  extra:
    social:
      - icon: fontawesome/brands/mastodon
        link: https://fosstodon.org/@squidfunk
    
  plugins: 
    - search:
        lang: pt-BR

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: custom-icons/icon-night
        name: Modo Claro
    
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: teal
      toggle:
        icon: custom-icons/icon-light
        name: Modo Escuro

markdown_extensions:
  - attr_list
  - md_in_html
  - mdx_math
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons 
  - footnotes 
  
nav:
  - Início: index.md
  - Guias de Contribuição:
    - Documentação: guias/documentacao.md
  - Requisitos:
    - Perfil dos usuários: requisitos/perfil_do_usuario.md
    - Entrevistas: requisitos/entrevistas.md
    - Introspecção: requisitos/introspeccao.md
    - Requisitos elicitados: requisitos/requisitos_elicitados.md
    - Priorização: requisitos/priorizacao.md
    - Histórias de usuário: requisitos/historias_de_usuario.md
  - Identidade Visual:
    - Logo: id_visual/logo.md
    - Cores: id_visual/cores.md
    # - Fontes:
    # - Icones:
    # - Componentes:

